In [3]:
print("a")

a


merhaba

herhangi başka şeylerde yazılabılır

yanı markdown kısmınde notlarımızı tutarız.
CODE kısmında kodlarımızı çalıştırırız.


In [4]:
merhaba


NameError: name 'merhaba' is not defined

# NEDEN NUMPY?

a= [1,2,3,4]
b= [2,3,4,5]
a

NOT: EN SON NEYI BIRAKIRSAK O ÇALIŞIR.burada a çalışır
HEM a Hem byi bırakırsam hem a yı hem b yı yazdırmaz. en son neyı yazdıysam onu yazdırır.
aşağıda oldugu gıbı.

In [5]:
a= [1,2,3,4]
b= [2,3,4,5]
a

[1, 2, 3, 4]

In [6]:
a= [1,2,3,4]
b= [2,3,4,5]
a
b

[2, 3, 4, 5]

# BAŞKA BİR ŞEY:

## İKİ LİSTE İLE İŞLEM YAPMAK İSTİYORUM: 2 listeyi çarpmak istiyorum.

In [ ]:
a= [1,2,3,4]
b= [2,3,4,5]

In [8]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i]*b[i])
              
ab

[2, 6, 12, 20]

biz mesela 2 listeyi çarpıcaz, bunun için böyle ugrasmak yerine boyle donguler yazmak
yerine numpy bize kolaylık sağlar ve kısa yolu getırır.

import numpy as np / numpy kutuphanelerını kullanmak için import kullanılır. dıs kutuphane ve modulleri içeriye dahıl etmek için import kullanılır.


In [9]:
import numpy as np

In [11]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])

In [12]:
a*b

array([ 2,  6, 12, 20])

# NUMPY ARRAY OLUŞTURMAK

In [15]:
import numpy as np

In [16]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [18]:
a=np.array([1,2,3,4,5])

In [19]:
type(a)

numpy.ndarray

numpy array sabıtlenmıs bir tiptir. ndarray olarak goruruz.

In [22]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

bu şekilde bütün sayıları ondalıklı bir forma çevirdi. sabit bir tip olarak 
karşımıza çıktı. sabit tip; her bir eleman için farklı bir tip istemıyorum. Sadece
bir tip, tek tip veri tutar. Eğer içinde 1 tane ondalıklı varsa hepsını ondalıklıya cevırır.

In [ ]:
import numpy as np

In [21]:
np.array([3.14,4,2,13])

array(['3.14', '4', 'meral', '2', '13'], dtype='<U32')

# AYRI ÖZEL BİR TİP OLUŞTURMAK İSTERSEM:

In [24]:
np.array([3.14,4,2,13], dtype="float32")

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

#float tipine cevırmıs oldu.

In [25]:
np.array([3.14,4,2,13], dtype="int")

array([ 3,  4,  2, 13])

#int tipine çevrilmiş oldu.

#SIFIRDAN ARRAY OLUŞTURMAK:

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

10 tane sıfırdan oluşan float tipte bir array oluştu. inte cevırelım.

In [27]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 1'lerden oluşan Array oluşturmak istersek:

In [28]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

sütün ve satırlardan oluşan array. int tipine cevırelım

In [29]:
np.ones((3,5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
Eğer sadece belirli tiplerden oluşan array oluşturmak istersem:
Mesela sadece 3lerden oluşturmak istiyorsak:

In [32]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

## Doğrusal Bir Dizi Nasıl Oluştururuz? 
mesala: 0'dan 31 e kadar 3'er 3'er artan bir array.

In [33]:
np.arange(0,31,3) 

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

## 2 DEĞER ARASINDA BELİRLİ SAYIDA DEĞER OLUŞTURMA

#Mesela 2 değer arasında 10 tane değer oluşturalım:

In [35]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## Önemli bir şey ;

Ben ortalamasını, standart sapmasını , ve kaça kaçlık matris olucagını
bileceğim bir array oluşturayım:

In [38]:
np.random.normal(10,4,(3,4))

array([[11.8533781 ,  9.19013208,  7.82601259, 11.10983986],
       [ 4.54347955, 13.77314099, 13.88886154,  9.89116494],
       [11.58495342,  8.37150105, 12.8178936 ,  7.91878865]])

10 ortama, 4 standart sapma, (3,4)luk matrıs. 
yanı ortalaması 10 olan, standart sapması 4 olan (3,4) lük bir matris olusturdum.

In [39]:
np.random.normal(10,4,(3,4))

array([[ 7.39916231,  9.43649787, 11.68255788,  3.56638854],
       [15.02424982,  8.90569229, 13.92983476,  7.12597892],
       [ 5.17732399, 15.10042941, 11.75836391, 12.78869718]])

Teorik anlamda, tek boyutlu arrin anlamı vektor
2 boyutlu arrayın anlamı matrıstır.
Dağılımını kendimiz belirlediğimiz, bir sayı üretme işlemini gerçekleştirdik.

# Ben dağılımla ilgilenmiyorum int uzerınden rastgele oluşturulmus
# veri üretmek istiyorum. np.random.randint

In [40]:
np.random.randint(0,10,(3,3))

array([[2, 5, 9],
       [1, 7, 0],
       [3, 0, 6]])

# SIKLIKLA KULLANDIGIMIZ VERİ SAYI ÜRETME FONKSIYONLARI;
# random.normal
# arange
# random.randint

# Numpy  Array Özellikleri:

* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [44]:
import numpy as np

In [46]:
np.random.randint(10,size=10)

array([6, 2, 3, 3, 9, 2, 6, 0, 3, 4])

bu durum 0'dan 10'a kadar rastgele sayı çıkarır. bunu a dıye bır degere kaydedelim.

In [47]:
a = np.random.randint(10,size=10)

In [48]:
a.ndim

1

tek boyutlu array oldugundan dolayı  1 çıkar

In [49]:
a.shape

(10,)

bir boyut var ve içinde 10 tane eleman var

In [50]:
a.size

10

In [51]:
a.dtype

dtype('int32')

#2 BOYUTLU ARRAY OLUŞTURMA VE ÖZELLİKLERİNİ İNCELEME:

In [52]:
b= np.random.randint(10,size=(3,5))

In [53]:
b

array([[9, 9, 5, 9, 9],
       [8, 0, 6, 7, 8],
       [4, 1, 4, 8, 6]])

In [54]:
b.ndim

2

In [55]:
b.shape

(3, 5)

In [56]:
b.size

15

In [58]:
b.dtype

dtype('int32')

## VAR OLAN NUMPY ARRAY'INI YENIDEN ŞEKİLLENDİRME(RESHAPING)

In [59]:
import numpy as np

In [60]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

3 boyuta çevirmek istersek: reshape methodu kullanılır.

In [62]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a=np.arange(1,10)

In [65]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
a.ndim

1

elımızdekı tek boyutlu arrayı ıkı boyutlu matrıse cevırmek istiyourz ama tek boyutludakı bılgısı de elımızde kalsın.


In [71]:
a.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
baktııgmızda iki ifade birbirine çok benzer fakat birinde ıkı koseli parantez,
birinde tek koselı parantez var. alttakı artık bır matrıstır. boyutu ıkıdır ama aynı sekılde
tek bır vektorun tasıdıgı bılgıyı tasır. ama 1 satır 9 sutundan olusur. b.ndim dedıgımızde 
2 boyut çıkar




In [72]:
b=a.reshape((1,9))

In [73]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [74]:
b.ndim

2

In [75]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
np.arange(1,9).reshape((2,2))

ValueError: cannot reshape array of size 8 into shape (2,2)

In [84]:
np.arange(1,5).reshape((2,2))

array([[1, 2],
       [3, 4]])

In [85]:
np.arange(5,9).reshape((2,2))

array([[5, 6],
       [7, 8]])

In [86]:
np.arange(5,10).reshape((2,2))

ValueError: cannot reshape array of size 5 into shape (2,2)

## ARRAY BİRLEŞTİRME ( CONCATENATION)

## Tek boyutta birleştirme

In [88]:
import numpy as np

In [90]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [91]:
np.concatenatıon([x,y])

AttributeError: module 'numpy' has no attribute 'concatenatıon'

AttributeError: module 'numpy' has no attribute 'concatenatıon'

bu hata da böyle bir fonksıyon yok demek istemiş. hemen duzeltelım.

In [92]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [ ]:
iki arrayi bırleştirdi.

başka bir z arrayı cıksın. bunu da kaydedebilir miyiz? bakıyoruz

In [94]:
z=np.array([7,8,9])

In [95]:
z

array([7, 8, 9])

In [96]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [98]:
a=np.concatenate([x,y])

In [99]:
a

array([1, 2, 3, 4, 5, 6])

In [100]:
np.concatenate([a,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## İki boyutlu Birleştirme

In [ ]:
iki boyutlu arraylerde ıkı koselı parantz kullanılır.

In [101]:
a=np.array([[1,2,3],[4,5,6]])

In [102]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

# satır bazında değil sütun bazında birleştirmek istersem:

In [104]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
axis eksen anlamına gelır. axis=0 satır bazıdır.
axis=1 sütun bazında eklemek demektir.

In [105]:
np.concatenate([a,a], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

# Array Ayırma (Splitting)

## TEK BOYUTLU ARRAY AYIRMA

In [115]:
import numpy as np

In [107]:
x = np.array([1,2,3,99,99,3,2,1])


In [108]:
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [109]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

bunu ayrı ayrı gormek istediğimde:

In [110]:
x = np.array([1,2,3,99,99,3,2,1])

In [111]:
a,b,c = np.split(x, [3,5])

In [112]:
a

array([1, 2, 3])

In [113]:
b

array([99, 99])

In [114]:
c

array([3, 2, 1])

## 2 Boyutlu Array Ayırma Dikey Boyutta

In [117]:
m= np.arange(16).reshape(4,4)

In [118]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [120]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

0 1 2ye kadar bol, 2 dahıl değil. 
üst ve alt diyerek 2 farklı şekilde yapabılırız. ayrı ayrı kullanmak ıstedıgımde.

In [123]:
ust,alt=np.vsplit(m,[2])

In [124]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [125]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## 2 Boyutlu Array Ayırma Yatay Boyutta

In [127]:
m= np.arange(16).reshape(4,4)

In [128]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [129]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [130]:
sag, sol = np.hsplit(m,[2])

In [131]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [132]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## ARRAY SIRALAMA (SORTING)

In [134]:
import numpy as np

In [135]:
v= np.array ([2,1,4,3,5])

In [136]:
v

array([2, 1, 4, 3, 5])

In [137]:
np.sort(v)

array([1, 2, 3, 4, 5])

küçükten büyüğe sıraladım..

## 2 Boyutla Sıralama / Array

In [139]:
m = np.random.normal(20,5,(3,3))

In [140]:
m

array([[14.08251211, 12.69971143, 20.69321591],
       [23.48503731, 16.70788636, 22.3513893 ],
       [31.00238236, 20.50467183, 27.30908905]])

ortalaması 20 olan, standart sapması 5 olan (3,3) olan bir array

## 2 Boyutlu Array satırlarını sıralayalım: küçükten büyüğe


In [143]:
np.sort(m, axis= 1)

array([[12.69971143, 14.08251211, 20.69321591],
       [16.70788636, 22.3513893 , 23.48503731],
       [20.50467183, 27.30908905, 31.00238236]])

## 2 Boyutlu Array sütunlarını sıralayalım: küçükten büyüğe

In [144]:
np.sort(m, axis= 0)

array([[14.08251211, 12.69971143, 20.69321591],
       [23.48503731, 16.70788636, 22.3513893 ],
       [31.00238236, 20.50467183, 27.30908905]])

## Index İle ELemanlara Erişmek

## Tek Boyutlu Arraylarda Index

In [146]:
import numpy as np
a= np.random.randint (10, size=10)
a

array([3, 3, 7, 1, 6, 2, 6, 2, 9, 0])

In [147]:
a[0]

3

In [148]:
a[-1]

0

-1 tersten erısım demek

In [149]:
a[5]

2

## a[0]=100 olmasını istiyoruz. / Indeks elemanına değiştirmek

In [150]:
a[0]=100

In [151]:
a

array([100,   3,   7,   1,   6,   2,   6,   2,   9,   0])

## 2 Boyutlu Arraylarda Index

In [154]:
import numpy as np

In [158]:
m= np.random.randint (10, size=(3,5))
m

array([[6, 5, 8, 3, 7],
       [6, 8, 8, 5, 5],
       [5, 1, 9, 7, 6]])

In [159]:
m[0,0]

6

In [160]:
m[1,1]

8

In [161]:
m[1,4]

5

## 2 Boyutlularda Arreylerde Index Değiştirme

In [162]:
m[1,4]=99

In [163]:
m

array([[ 6,  5,  8,  3,  7],
       [ 6,  8,  8,  5, 99],
       [ 5,  1,  9,  7,  6]])

## 2 Boyutlularda Arreylerde Float Index Ekleme

In [165]:
m[1,4]=2.2

In [166]:
m

array([[6, 5, 8, 3, 7],
       [6, 8, 8, 5, 2],
       [5, 1, 9, 7, 6]])

In [ ]:
başka tipte bır ekleme yapınca kabul  etmedı. var olan bır arraye başka bir
tip ekleyınce kabul etmedı.

## SLICING İLE ELEMANLARA ERİŞMEK (ARRAY ALT KÜMESİNE ERİŞMEK)

## Tek boyutlu slice işlemleri

In [169]:
import numpy as np

In [170]:
a= np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [171]:
a[0:3]

array([20, 21, 22])

In [172]:
a[:3]

array([20, 21, 22])

In [173]:
a[0:3]

array([20, 21, 22])

In [175]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [176]:
a[1::2]

array([21, 23, 25, 27, 29])

In [177]:
a[0::2]

array([20, 22, 24, 26, 28])

## 2 boyutlu slice işlemleri

In [178]:
m= np.random.randint(10, size= (5,5))

In [179]:
m

array([[5, 5, 0, 9, 7],
       [2, 2, 4, 7, 0],
       [3, 0, 6, 3, 4],
       [2, 4, 7, 0, 6],
       [5, 2, 9, 3, 4]])

Bütün satırları seç, 0. sütunu seç

In [182]:
m[:,0]

array([5, 2, 3, 2, 5])

bütün satırları seç, 1.sütunu seç

In [183]:
m[:,1]

array([5, 2, 0, 4, 2])

Satırlarda seçme işlemi

In [186]:
m[0,:]

array([5, 5, 0, 9, 7])

In [187]:
m[1,:]

array([2, 2, 4, 7, 0])

SATIR VE SÜTUNLARA ERİŞMEK

In [189]:
m[0:2, 0:3]

array([[5, 5, 0],
       [2, 2, 4]])

In [191]:
m[::,:2]

array([[5, 5],
       [2, 2],
       [3, 0],
       [2, 4],
       [5, 2]])

## Alt Küme Üzerinde İşlem Yapmak

In [193]:
import numpy as np

In [194]:
a=np.random.randint(10, size=(5,5))

In [195]:
a

array([[2, 5, 3, 9, 5],
       [0, 4, 6, 4, 7],
       [3, 6, 1, 7, 8],
       [1, 4, 7, 0, 8],
       [4, 1, 0, 4, 0]])

In [196]:
alt_a=a[0:3, 0:2]

In [197]:
alt_a

array([[2, 5],
       [0, 4],
       [3, 6]])

In [198]:
alt_a[0,0]=9999
alt_a[1,1]=888

In [199]:
alt_a

array([[9999,    5],
       [   0,  888],
       [   3,    6]])

In [200]:
a

array([[9999,    5,    3,    9,    5],
       [   0,  888,    6,    4,    7],
       [   3,    6,    1,    7,    8],
       [   1,    4,    7,    0,    8],
       [   4,    1,    0,    4,    0]])

In [ ]:
Alt kume üzerinde değişiklik yapınca tüm kümede değişiklik yapmış olur.

Ana parçamızı bozmamak istemeyız bazen, bazen arrayın alt kumesınde degısıklık yapmak
isteriz. Ana arrayımız bozmak istemeyız. bunun ıcın copy metodu kullanırız.

In [201]:
m=np.random.randint(10, size=(5,5))
m

array([[1, 0, 0, 2, 4],
       [7, 6, 2, 9, 7],
       [2, 1, 3, 9, 0],
       [4, 3, 2, 1, 6],
       [9, 6, 3, 8, 3]])

In [202]:
alt_b=m[0:3, 0:2].copy()

In [ ]:
copy metodu ana arrayden bagımsızlastırdı

In [203]:
alt_b

array([[1, 0],
       [7, 6],
       [2, 1]])

In [204]:
alt_b[0,0]=9999


In [205]:
alt_b

array([[9999,    0],
       [   7,    6],
       [   2,    1]])

In [206]:
m

array([[1, 0, 0, 2, 4],
       [7, 6, 2, 9, 7],
       [2, 1, 3, 9, 0],
       [4, 3, 2, 1, 6],
       [9, 6, 3, 8, 3]])

olusturdugumuz oldugumuz ilk arrayın yapısında hıcbır degıısılık olmadı. 
alt kumede degıısklık meydana gelmış oldu

## Fancy ındex ile Elemanlara Erişmek

## tek boyutta fancy

In [207]:
import numpy as np
v= np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [208]:
v[1]

3

In [209]:
v[5]

15

In [210]:
v[3]

9

bunları bırarada görmek istersem:

In [212]:
[v[1],v[3],v[5]]

[3, 9, 15]

#fency işlemi ile kolay yoldan yapmak:

In [214]:
al_getir=[1,3,5]

In [215]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [216]:
v[al_getir]

array([ 3,  9, 15])

## iki boyutta fancy

In [218]:
m=np.arange(9).reshape((3,3))

In [219]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [220]:
satir=np.array([0,1])
sutun=np.array([1,2])

In [221]:
m[satir,sutun]

array([1, 5])

## Basıt index ile FANCY iNDEX

In [223]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [224]:
m[0,[1,2]]

array([1, 2])

# slice ile fancy

In [225]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Koşullu Eleman İşlemleri

In [227]:
import numpy as np
v=np.array([1,2,3,4,5])

In [228]:
v

array([1, 2, 3, 4, 5])

In [229]:
v>5

array([False, False, False, False, False])

In [230]:
v<3

array([ True,  True, False, False, False])

In [231]:
v[v>3]

array([4, 5])

In [232]:
v[v>=3]

array([3, 4, 5])

In [235]:
v[v==3]

array([3])

In [236]:
v[v!=3]

array([1, 2, 4, 5])

In [240]:
v

array([1, 2, 3, 4, 5])

In [241]:
v**2

array([ 1,  4,  9, 16, 25])

## Matematiksel İşlemler

In [237]:
import numpy as np

In [238]:
v=np.array([1,2,3,4,5])

In [239]:
v

array([1, 2, 3, 4, 5])

In [242]:
v-1

array([0, 1, 2, 3, 4])

In [243]:
v*5

array([ 5, 10, 15, 20, 25])

## Ufunc Metodu! 

In [244]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [245]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [246]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [247]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [248]:
v**2

array([ 1,  4,  9, 16, 25])

In [249]:
v**3


array([  1,   8,  27,  64, 125], dtype=int32)

In [250]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [251]:
v%2

array([1, 0, 1, 0, 1], dtype=int32)

In [252]:
np.mod(v,2)


array([1, 0, 1, 0, 1], dtype=int32)

In [255]:
np.absolute(np.array([-3]))

array([3])

In [256]:
np.sin(360)

0.9589157234143065

In [257]:
np.cos(360)


-0.2836910914865273

In [258]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [259]:
np.log10(v)



array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

## numpy ile ilgili bilgilere nasıl ulaşıcaz?

In [260]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Lenovo\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\lenovo\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

## cheatsheet numpy yazarak onumuze cıktı cıkar googlayarak onumuze bır suru sey cıkar


In [ ]:
numpy statistics 

In [ ]:
Numpy İle 2 Bilinmeyenli Denklem

In [263]:
import numpy as np

NameError: name 'fdsfgrd' is not defined